update touchin generamba template
TouchInstinct/generamba_templates pull request #13
Opened 2018-12-29 15:48 UTC by kopytovs

2018-12-29 15:55 UTC, iON1k approved these changes

2018-12-29 15:55 UTC, petropavel13 requested changes

2018-12-29 15:55 UTC, petropavel13 commented on touchin/Code/ViewModel/view_model.swift.liquid
> +private enum Constants {
remove

2018-12-29 15:55 UTC, petropavel13 commented on touchin/Code/View/view_controller.swift.liquid
> +private enum Constants {
remove

2018-12-29 15:55 UTC, petropavel13 commented on touchin/Code/View/view_controller.swift.liquid
> +final class {{ module_info.name }}ViewController: BaseViewController<{{ module_info.name }}ViewModel> {
BaseConfigurableController

2018-12-29 15:55 UTC, petropavel13 commented on touchin/Code/View/view_controller.swift.liquid
> +// MARK: - Constraints
did you mean public?

2018-12-29 15:55 UTC, petropavel13 commented on touchin/Code/View/view_controller.swift.liquid
> +// MARK: - Action
what for?
objc actions will be inside class

2018-12-29 15:55 UTC, petropavel13 commented on touchin/Code/ViewModel/view_model.swift.liquid
> +//MARK: - Public
add space

2018-12-29 15:55 UTC, petropavel13 commented on touchin/Code/ViewModel/view_model.swift.liquid
> +//MARK: - Actions
smae

2018-12-29 15:55 UTC, petropavel13 commented on touchin/Code/ViewModel/view_model.swift.liquid
> +//MARK: - Private
same

2018-12-29 15:55 UTC, petropavel13 commented on touchin/Code/ViewModel/view_model.swift.liquid
> +    // MARK: - Life Cycle
life cycle for view model?

2018-12-29 15:55 UTC, petropavel13 commented on touchin/Code/ViewModel/view_model.swift.liquid
> +final class {{ module_info.name }}ViewModel: BaseControllerViewModel {
BaseViewModel

2018-12-29 16:06 UTC, kopytovs commented on touchin/Code/ViewModel/view_model.swift.liquid
> +    // MARK: - Life Cycle
meant `init`

2018-12-29 16:11 UTC, petropavel13 requested changes

2018-12-29 16:11 UTC, petropavel13 commented on touchin/Code/View/view_controller.swift.liquid
>      override func viewDidLoad() {
remove

2018-12-29 16:11 UTC, petropavel13 commented on touchin/Code/View/view_controller.swift.liquid
> +// MARK: - Constraints
rename to public

2018-12-29 16:11 UTC, petropavel13 commented on touchin/Code/View/view_controller.swift.liquid
> +final class {{ module_info.name }}ViewController: BaseConfigurableController<{{ module_info.name }}ViewModel>, DisposeBagHolder {
DisposeBagHolder is not implemented

2018-12-29 16:38 UTC, petropavel13 requested changes

2018-12-29 16:38 UTC, petropavel13 commented on touchin/Code/View/view_controller.swift.liquid
> +    var disposeBag = DisposeBag()
private let

2019-01-09 09:19 UTC, petropavel13 approved these changes

2019-01-09 09:20 UTC, merged