fix page increment on failed response
TouchInstinct/generamba_templates pull request #7
Opened 2018-03-29 15:19 UTC by petropavel13

2018-03-29 15:21 UTC, scoreyou approved these changes

2018-04-02 09:02 UTC, igorkislyuk commented
- add to readme another templates
- fix please fileprivate [here](https://github.com/TouchInstinct/generamba_templates/blob/f62325ad232cc7a7c1a2491afbf2559490ec2bf9/touchin-tablecell/TableCell/cell.swift.liquid#L9)

2018-04-02 09:02 UTC, igorkislyuk requested changes
- add to readme another templates
- fix please fileprivate [here](https://github.com/TouchInstinct/generamba_templates/blob/f62325ad232cc7a7c1a2491afbf2559490ec2bf9/touchin-tablecell/TableCell/cell.swift.liquid#L9)

2018-04-02 10:50 UTC, igorkislyuk approved these changes

2018-04-02 10:52 UTC, merged